### ISSUE TITLE
Make basic REST API use MySQL

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [aidan-plenert-macdonald/mousetrap#1]
A MySQL container is built into the [docker-compose stack](https://github.com/aidan-plenert-macdonald/mousetrap/blob/master/docker-compose.yml#L11). The current webapp is [setting up a connection](https://github.com/aidan-plenert-macdonald/mousetrap/blob/master/webapp/server.js#L9) to this database, but not actually using it for the REST API's.

Using the [NodeJS package mysql](https://www.npmjs.com/package/mysql) that is already [built into the webapp](https://github.com/aidan-plenert-macdonald/mousetrap/blob/master/webapp/package.json#L11), replace the current [GET](https://github.com/aidan-plenert-macdonald/mousetrap/blob/master/webapp/server.js#L26) and POST API's to make use of the database.

As a first step, make the GET return all mice in the SQL mice table. You will need to [create the table if it does not exist](https://dev.mysql.com/doc/refman/5.5/en/creating-tables.html). And the POST should [insert a record](https://dev.mysql.com/doc/refman/8.0/en/insert.html) into the SQL table, again creating the table if it does not exist.

If you would like to practice SQL without writing code, launch the stack according to the README and in a separate terminal run,

```
# Get the name of your webapp container (probably mousetrap_webapp_1)
$ docker ps
# Open a shell in the container
$ docker exec -it mousetrap_webapp_1 sh
# You are now in your container
/usr/src/app # apk add --no-cache mysql-client
/usr/src/app # mysql -prootable -h database mice
```

**Note** That there may be some bugs with the MySQL/MariaDB where the normal user and password defined in the docker-compose.yml doesn't work. We can figure this out later.

**Comment by Tapudp** [comment]
Should I directly look at the `server.js` file and look/modify the routes there? This would be my first Open Source project to work on so can you please help me/explain me that why is there is no other structure modularising the Routes files separately in their own folder?

**Comment by aidan-plenert-macdonald** [comment]
@Tapudp Thank you for your interest, but this project is designed to teach a class. Feel free to fork the repo, but I will only be taking contributions from class members. If you are interested in working on open source projects, I would recommend looking [Trending projects](https://github.com/explore?since=monthly&trending=repositories#trending) or better find an open source tool that you use a lot and contribute to that.

**Comment by Tapudp** [comment]
@aidan-plenert-macdonald oohhh I see DAMN IT (sorry), I was really interested in working on this since MySQL is newer for I me I even forked and tried out the basic routing with it like this.

`router.get('/', function(req, res, next) {
	res.locals.connection.query('SELECT * from users', function (error, results, fields) {
		if (error) throw error;
		res.send(JSON.stringify({"status": 200, "error": null, "response": results}));
	});
});`

I hope it was correct, I really like to play around with Node.js/Express.js apps especially creating JSON APIs with it and using newer ones. Thank you for your suggestion I will definitely try out to improve some library or tools that I am using currently. 

Thanks again for the quick and interesting response. Even in future if you can please accept my contribution let me know I am so eager to do so. 🥇 ❤️

**Comment by aidan-plenert-macdonald** [comment]
https://github.com/nicolaskruchten/pivottable/wiki/Input-Formats#arrays-of-objects

Be sure to output in a Pivot table supported format

**Comment by aidan-plenert-macdonald** [comment]
This is how it should be done, https://www.npmjs.com/package/mysql#getting-the-id-of-an-inserted-row

```
connection.query('INSERT INTO posts SET ?', {title: 'test'}, function (error, results, fields) {
  if (error) throw error;
  console.log(results.insertId);
});
```

Note that its not clear that `req.data` is of the right format https://github.com/aidan-plenert-macdonald/mousetrap/blob/issue01/webapp/server.js#L51
