### ISSUE TITLE
Build a web ui using @material-ui/core

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [aidan-plenert-macdonald/mousetrap#20]
https://www.npmjs.com/package/@material-ui/core

Look at the demos and build something with a menu and a web form https://github.com/mui-org/material-ui/tree/master/docs/src/pages/demos

For example, here is an example web form https://material-ui.com/demos/text-fields/. Click the github link to see the source.

A menu example is https://material-ui.com/demos/app-bar/. A good example is the App bar with a Menu. https://github.com/mui-org/material-ui/blob/master/docs/src/pages/demos/app-bar/MenuAppBar.js

**Comment by aidan-plenert-macdonald** [comment]
[Example](https://cdn-images-1.medium.com/max/1600/0*UnTqJBfMQrCxay8Q.png)

[Example](https://d85wutc1n854v.cloudfront.net/live/products/600x375/WB0074879.png?v=1.1.0)

**Comment by PotatoBob** [comment]
Added appbar that opens when we click the hamburger. Need to modify overlay.
