### ISSUE TITLE
Figure out how to add React with Express

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [aidan-plenert-macdonald/mousetrap#7]
Purely a research issue. Research [react.js](https://reactjs.org/) and figure out how to add it into the Express backend. ReactJS would be our front end.

Create more Github issues for tasks that would need to be done.

**Comment by matthew86707** [comment]
See [this](https://medium.com/front-end-hacking/getting-started-with-your-react-app-with-express-server-1c701a3c6edb)
